/**
 * MIT License
 * 
 * Copyright (c) 2025 Felipe Rodriguez Herrera
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import { useReducer } from "react";
import { useK } from "./useKeep";
import { KeepType } from "./keep";



const echo = <T>(t: T) => t;

/**
 * A custom React hook that manages state using a Keep pattern generator function.
 * 
 * @template K - The type of the value managed by the Keep pattern
 * @param generator - A function that returns a KeepType instance for managing state
 * @returns A readonly tuple containing the current value and the KeepType instance
 * 
 * @example
 * ```typescript
 * const [count, countKeeper] = useKpro(() => keep(0));
 * ```
 */
export function useKpr<K>(generator: () => KeepType<K> ) : readonly [K, KeepType<K>]; 


/**
 * A custom React hook that use a custom state object that contains KeepType properties. These keep properties are selected using a selector function.
 * 
 * @template S - The type of the state object generated by the generator function
 * @template T - A readonly array type extending KeepType for type-safe property selection
 * 
 * @param generator - A function that generates and returns the initial state object
 * @param selector - A function that takes the state object and returns an array of KeepType properties to use
 * 
 * @returns A readonly tuple containing the extracted values from the KeepType objects followed by the original state
 * 
 * @example
 * ```typescript
 * const [count, name, stateObject] = useKpro(
 *   () => ({count: keep(0), name: keep("default"), ...keepActions}),
 *   o => [o.count, o.name)]
 * );
 * ```
 */
export function useKpr<S, T extends readonly KeepType<any>[]>(
      generator: () => S, 
      selector: (s: S) => [...T]
    ): readonly [...{ [K in keyof T]: T[K] extends KeepType<infer U> ? U : never }, S];


export function useKpr<S, T extends readonly KeepType<any>[]>(generator: () => S, selector?: (s: S) => [...T] ) {
  const [objS] = useReducer(echo, generator());

  if (selector)
    return [...(selector(objS).map(useK) as { [K in keyof T]: T[K] extends KeepType<infer S> ? S : never } ), objS] as const

  return [useK(objS as KeepType<any>), objS] as const;
};
