/**
 * MIT License
 * 
 * Copyright (c) 2025 Felipe Rodriguez Herrera
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import { useReducer } from "react";
import { useKeep } from "./useKeep";
import { KeepType } from "./keep";



const echo = <T>(t: T) => t;


export function useKpro<S, T extends readonly KeepType<any>[]>(
      generator: () => S, 
      selector: (s: S) => [...T]
    ): readonly [...{ [K in keyof T]: T[K] extends KeepType<infer U> ? U : never }, S];
export function useKpro<S, K, M>(generator: () => S ) : [M extends KeepType<infer K> ? K : never, S]; 
/**
 * A React hook for use a generator of Keep stores and handlers to use in local component state.
 * 
 * @template S - The type of the state object generated by the generator function
 * @template T - A readonly array of KeepType objects that extends KeepType<any>[]
 * 
 * @param generator - A function that returns the initial state object of type S
 * @param selector - A function that takes the state object and returns an array of KeepType objects to be managed
 * 
 * @returns A readonly tuple containing:
 *   - The resolved values from each KeepType object (transformed through useKeep)
 *   - The original state object from the generator
 * 
 * @example
 * ```typescript
 * const [value1, value2, state] = useKpro(
 *   () => ({ keepA: someKeepType, keepB: anotherKeepType }),
 *   (s) => [s.keepA, s.keepB]
 * );
 * ```
 */
export function useKpro<S, T extends readonly KeepType<any>[]>(generator: () => S, selector?: (s: S) => [...T] ) {
  const [objS] = useReducer(echo, generator());

  if (selector)
    return [...(selector(objS).map(k => useKeep(k)) as { [K in keyof T]: T[K] extends KeepType<infer S> ? S : never } ), objS] as const

  return [useKeep(objS as unknown as KeepType<any>), objS] as const;
};
